// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHM-n8v89HI_YrfDROJF0avJm8DIiGCQo',
    appId: '1:604682309294:web:11384f27d621645319a73f',
    messagingSenderId: '604682309294',
    projectId: 'pcplus-305c6',
    authDomain: 'pcplus-305c6.firebaseapp.com',
    storageBucket: 'pcplus-305c6.appspot.com',
    measurementId: 'G-XCTSGVL9KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX7thSf10rFXEcoMt2YNEPf70n6cxkAOY',
    appId: '1:604682309294:android:5d08606bb9d2e36d19a73f',
    messagingSenderId: '604682309294',
    projectId: 'pcplus-305c6',
    storageBucket: 'pcplus-305c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyeP_z8uflU7PiJXwyZm5PN_VJGaJYi4s',
    appId: '1:604682309294:ios:24678fd19a7da97319a73f',
    messagingSenderId: '604682309294',
    projectId: 'pcplus-305c6',
    storageBucket: 'pcplus-305c6.appspot.com',
    iosBundleId: 'com.example.pcplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyeP_z8uflU7PiJXwyZm5PN_VJGaJYi4s',
    appId: '1:604682309294:ios:24678fd19a7da97319a73f',
    messagingSenderId: '604682309294',
    projectId: 'pcplus-305c6',
    storageBucket: 'pcplus-305c6.appspot.com',
    iosBundleId: 'com.example.pcplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHM-n8v89HI_YrfDROJF0avJm8DIiGCQo',
    appId: '1:604682309294:web:147667a7f6096cf519a73f',
    messagingSenderId: '604682309294',
    projectId: 'pcplus-305c6',
    authDomain: 'pcplus-305c6.firebaseapp.com',
    storageBucket: 'pcplus-305c6.appspot.com',
    measurementId: 'G-X3Z5VKP7G8',
  );
}
